// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/generate-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/generate-code.post').default>>>>
    }
    '/api/admin/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/members.get').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/toggle-member': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/toggle-member.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/auth/staff-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/staff-login.post').default>>>>
    }
    '/api/tickets/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/create.post').default>>>>
    }
    '/api/tickets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/index.get').default>>>>
    }
    '/api/tickets/message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/message.post').default>>>>
    }
    '/api/tickets/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/update.post').default>>>>
    }
    '/api/user/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/me.get').default>>>>
    }
    '/api/user/save-data': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/save-data.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}